/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres"
import { relations } from "@payloadcms/db-postgres/drizzle"
import {
  boolean,
  foreignKey,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  serial,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "@payloadcms/db-postgres/drizzle/pg-core"
export const enum_users_roles = pgEnum("enum_users_roles", [
  "admin",
  "customer",
])
export const enum_users_gender = pgEnum("enum_users_gender", ["male", "female"])
export const enum_addresses_title = pgEnum("enum_addresses_title", [
  "mr",
  "ms",
  "mrs",
  "dr",
  "prof",
])
export const enum_categories_type = pgEnum("enum_categories_type", [
  "product",
  "post",
])
export const enum_orders_payment_status = pgEnum("enum_orders_payment_status", [
  "unpaid",
  "paid",
  "refunded",
])
export const enum_order_statuses_status = pgEnum("enum_order_statuses_status", [
  "pending",
  "processing",
  "shipped",
  "delivered",
  "cancelled",
])

export const users_roles = pgTable(
  "users_roles",
  {
    order: integer("order").notNull(),
    parent: uuid("parent_id").notNull(),
    value: enum_users_roles("value"),
    id: uuid("id").defaultRandom().primaryKey(),
  },
  (columns) => [
    index("users_roles_order_idx").on(columns.order),
    index("users_roles_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [users.id],
      name: "users_roles_parent_fk",
    }).onDelete("cascade"),
  ]
)

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ]
)

export const users = pgTable(
  "users",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    isActive: boolean("is_active").notNull().default(true),
    firstName: varchar("first_name").notNull(),
    lastName: varchar("last_name").notNull(),
    gender: enum_users_gender("gender").notNull(),
    paystackCustomerCode: varchar("paystack_customer_code").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    _verified: boolean("_verified"),
    _verificationToken: varchar("_verificationtoken"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ]
)

export const addresses = pgTable(
  "addresses",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    user: uuid("user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    title: enum_addresses_title("title").notNull(),
    firstName: varchar("first_name").notNull(),
    lastName: varchar("last_name").notNull(),
    phone: varchar("phone").notNull(),
    label: varchar("label"),
    line1: varchar("line1").notNull(),
    line2: varchar("line2"),
    area: varchar("area"),
    landmark: varchar("landmark"),
    city: varchar("city").notNull(),
    county: varchar("county").notNull(),
    country: varchar("country").notNull().default("Kenya"),
    postalCode: varchar("postal_code").notNull(),
    note: varchar("note"),
    isDefault: boolean("is_default").notNull().default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("addresses_user_idx").on(columns.user),
    index("addresses_updated_at_idx").on(columns.updatedAt),
    index("addresses_created_at_idx").on(columns.createdAt),
  ]
)

export const media = pgTable(
  "media",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    alt: varchar("alt"),
    prefix: varchar("prefix").default("media"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ]
)

export const media_texts = pgTable(
  "media_texts",
  {
    id: serial("id").primaryKey(),
    order: integer("order").notNull(),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    text: varchar("text"),
  },
  (columns) => [
    index("media_texts_order_parent").on(columns.order, columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [media.id],
      name: "media_texts_parent_fk",
    }).onDelete("cascade"),
  ]
)

export const packages = pgTable(
  "packages",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    generateSlug: boolean("generate_slug").default(true),
    slug: varchar("slug").notNull(),
    isActive: boolean("is_active").notNull().default(true),
    title: varchar("title").notNull(),
    length: numeric("length", { mode: "number" }).notNull(),
    width: numeric("width", { mode: "number" }).notNull(),
    height: numeric("height", { mode: "number" }).notNull(),
    maxWeight: numeric("max_weight", { mode: "number" }).notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("packages_slug_idx").on(columns.slug),
    uniqueIndex("packages_title_idx").on(columns.title),
    index("packages_updated_at_idx").on(columns.updatedAt),
    index("packages_created_at_idx").on(columns.createdAt),
  ]
)

export const service_areas_shipping_rates = pgTable(
  "service_areas_shipping_rates",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    package: uuid("package_id")
      .notNull()
      .references(() => packages.id, {
        onDelete: "set null",
      }),
    price: numeric("price", { mode: "number" }).notNull(),
  },
  (columns) => [
    index("service_areas_shipping_rates_order_idx").on(columns._order),
    index("service_areas_shipping_rates_parent_id_idx").on(columns._parentID),
    index("service_areas_shipping_rates_package_idx").on(columns.package),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [service_areas.id],
      name: "service_areas_shipping_rates_parent_id_fk",
    }).onDelete("cascade"),
  ]
)

export const service_areas = pgTable(
  "service_areas",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    generateSlug: boolean("generate_slug").default(true),
    slug: varchar("slug").notNull(),
    isActive: boolean("is_active").notNull().default(true),
    title: varchar("title").notNull(),
    deliveryTime_minDays: numeric("delivery_time_min_days", {
      mode: "number",
    }).notNull(),
    deliveryTime_maxDays: numeric("delivery_time_max_days", {
      mode: "number",
    }).notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("service_areas_slug_idx").on(columns.slug),
    uniqueIndex("service_areas_title_idx").on(columns.title),
    index("service_areas_updated_at_idx").on(columns.updatedAt),
    index("service_areas_created_at_idx").on(columns.createdAt),
  ]
)

export const brands = pgTable(
  "brands",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    generateSlug: boolean("generate_slug").default(true),
    slug: varchar("slug").notNull(),
    isActive: boolean("is_active").notNull().default(true),
    title: varchar("title").notNull(),
    supplierImageUrl: varchar("supplier_image_url"),
    logo: uuid("logo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("brands_slug_idx").on(columns.slug),
    uniqueIndex("brands_title_idx").on(columns.title),
    index("brands_logo_idx").on(columns.logo),
    index("brands_updated_at_idx").on(columns.updatedAt),
    index("brands_created_at_idx").on(columns.createdAt),
  ]
)

export const categories_type = pgTable(
  "categories_type",
  {
    order: integer("order").notNull(),
    parent: uuid("parent_id").notNull(),
    value: enum_categories_type("value"),
    id: uuid("id").defaultRandom().primaryKey(),
  },
  (columns) => [
    index("categories_type_order_idx").on(columns.order),
    index("categories_type_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [categories.id],
      name: "categories_type_parent_fk",
    }).onDelete("cascade"),
  ]
)

export const categories = pgTable(
  "categories",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    generateSlug: boolean("generate_slug").default(true),
    slug: varchar("slug").notNull(),
    isActive: boolean("is_active").notNull().default(true),
    title: varchar("title").notNull(),
    description: varchar("description"),
    srcUrl: varchar("src_url"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("categories_slug_idx").on(columns.slug),
    index("categories_updated_at_idx").on(columns.updatedAt),
    index("categories_created_at_idx").on(columns.createdAt),
  ]
)

export const products = pgTable(
  "products",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    isActive: boolean("is_active").notNull().default(true),
    generateSlug: boolean("generate_slug").default(true),
    slug: varchar("slug").notNull(),
    title: varchar("title").notNull(),
    brand: uuid("brand_id")
      .notNull()
      .references(() => brands.id, {
        onDelete: "set null",
      }),
    origin: varchar("origin"),
    supplierImageUrl: varchar("supplier_image_url"),
    productInformation: varchar("product_information"),
    nutritionalInformation: varchar("nutritional_information"),
    supplierUrl: varchar("supplier_url"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("products_slug_idx").on(columns.slug),
    index("products_brand_idx").on(columns.brand),
    index("products_updated_at_idx").on(columns.updatedAt),
    index("products_created_at_idx").on(columns.createdAt),
  ]
)

export const products_rels = pgTable(
  "products_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    mediaID: uuid("media_id"),
    categoriesID: uuid("categories_id"),
  },
  (columns) => [
    index("products_rels_order_idx").on(columns.order),
    index("products_rels_parent_idx").on(columns.parent),
    index("products_rels_path_idx").on(columns.path),
    index("products_rels_media_id_idx").on(columns.mediaID),
    index("products_rels_categories_id_idx").on(columns.categoriesID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [products.id],
      name: "products_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "products_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["categoriesID"]],
      foreignColumns: [categories.id],
      name: "products_rels_categories_fk",
    }).onDelete("cascade"),
  ]
)

export const product_variants = pgTable(
  "product_variants",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    generateSlug: boolean("generate_slug").default(true),
    slug: varchar("slug").notNull(),
    isActive: boolean("is_active").notNull().default(true),
    sku: varchar("sku").notNull(),
    title: varchar("title").notNull(),
    detailTitle: varchar("detail_title"),
    size: varchar("size"),
    flavorColor: varchar("flavor_color"),
    variant: varchar("variant"),
    product: uuid("product_id")
      .notNull()
      .references(() => products.id, {
        onDelete: "set null",
      }),
    category: varchar("category"),
    supplierPrice: numeric("supplier_price", { mode: "number" }),
    supplierDiscountedPrice: numeric("supplier_discounted_price", {
      mode: "number",
    }),
    priceFetchedAt: timestamp("price_fetched_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    costPrice: numeric("cost_price", { mode: "number" }),
    retailPrice: numeric("retail_price", { mode: "number" }),
    stock: numeric("stock", { mode: "number" }).notNull().default(0),
    supplierStock: numeric("supplier_stock", { mode: "number" }),
    onPallet: numeric("on_pallet", { mode: "number" }),
    inCase: numeric("in_case", { mode: "number" }),
    expiryDate: timestamp("expiry_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    weight: numeric("weight", { mode: "number" }),
    servingSizePerContainer: numeric("serving_size_per_container", {
      mode: "number",
    }),
    servingSize: numeric("serving_size", { mode: "number" }),
    supplierProductCode: varchar("supplier_product_code"),
    barcode: varchar("barcode"),
    exportCommodityCode: varchar("export_commodity_code"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("product_variants_slug_idx").on(columns.slug),
    uniqueIndex("product_variants_sku_idx").on(columns.sku),
    index("product_variants_title_idx").on(columns.title),
    index("product_variants_detail_title_idx").on(columns.detailTitle),
    index("product_variants_product_idx").on(columns.product),
    index("product_variants_barcode_idx").on(columns.barcode),
    index("product_variants_updated_at_idx").on(columns.updatedAt),
    index("product_variants_created_at_idx").on(columns.createdAt),
  ]
)

export const product_variants_rels = pgTable(
  "product_variants_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    mediaID: uuid("media_id"),
  },
  (columns) => [
    index("product_variants_rels_order_idx").on(columns.order),
    index("product_variants_rels_parent_idx").on(columns.parent),
    index("product_variants_rels_path_idx").on(columns.path),
    index("product_variants_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [product_variants.id],
      name: "product_variants_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "product_variants_rels_media_fk",
    }).onDelete("cascade"),
  ]
)

export const stock_alerts = pgTable(
  "stock_alerts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    user: uuid("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    productVariant: uuid("product_variant_id")
      .notNull()
      .references(() => product_variants.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("stock_alerts_user_idx").on(columns.user),
    index("stock_alerts_product_variant_idx").on(columns.productVariant),
    index("stock_alerts_updated_at_idx").on(columns.updatedAt),
    index("stock_alerts_created_at_idx").on(columns.createdAt),
    uniqueIndex("user_productVariant_idx").on(
      columns.user,
      columns.productVariant
    ),
  ]
)

export const wishlists = pgTable(
  "wishlists",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    customer: uuid("customer_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    productVariant: uuid("product_variant_id")
      .notNull()
      .references(() => product_variants.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("wishlists_customer_idx").on(columns.customer),
    index("wishlists_product_variant_idx").on(columns.productVariant),
    index("wishlists_updated_at_idx").on(columns.updatedAt),
    index("wishlists_created_at_idx").on(columns.createdAt),
    uniqueIndex("customer_productVariant_idx").on(
      columns.customer,
      columns.productVariant
    ),
  ]
)

export const carts_items = pgTable(
  "carts_items",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    productVariant: uuid("product_variant_id")
      .notNull()
      .references(() => product_variants.id, {
        onDelete: "set null",
      }),
    quantity: numeric("quantity", { mode: "number" }).notNull(),
    snapshot_retailPrice: numeric("snapshot_retail_price", { mode: "number" }),
    snapshot_inventoryStock: numeric("snapshot_inventory_stock", {
      mode: "number",
    }),
    snapshot_supplierStock: numeric("snapshot_supplier_stock", {
      mode: "number",
    }),
  },
  (columns) => [
    index("carts_items_order_idx").on(columns._order),
    index("carts_items_parent_id_idx").on(columns._parentID),
    index("carts_items_product_variant_idx").on(columns.productVariant),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [carts.id],
      name: "carts_items_parent_id_fk",
    }).onDelete("cascade"),
  ]
)

export const carts = pgTable(
  "carts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    customer: uuid("customer_id").references(() => users.id, {
      onDelete: "set null",
    }),
    guestSessionId: varchar("guest_session_id"),
    lastActiveAt: timestamp("last_active_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("carts_customer_idx").on(columns.customer),
    uniqueIndex("carts_guest_session_id_idx").on(columns.guestSessionId),
    index("carts_updated_at_idx").on(columns.updatedAt),
    index("carts_created_at_idx").on(columns.createdAt),
  ]
)

export const orders_items = pgTable(
  "orders_items",
  {
    _order: integer("_order").notNull(),
    _parentID: numeric("_parent_id", { mode: "number" }).notNull(),
    id: varchar("id").primaryKey(),
    productVariant: uuid("product_variant_id")
      .notNull()
      .references(() => product_variants.id, {
        onDelete: "set null",
      }),
    quantity: numeric("quantity", { mode: "number" }).notNull(),
    snapshot: jsonb("snapshot").notNull(),
  },
  (columns) => [
    index("orders_items_order_idx").on(columns._order),
    index("orders_items_parent_id_idx").on(columns._parentID),
    index("orders_items_product_variant_idx").on(columns.productVariant),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [orders.id],
      name: "orders_items_parent_id_fk",
    }).onDelete("cascade"),
  ]
)

export const orders = pgTable(
  "orders",
  {
    id: numeric("id", { mode: "number" }).primaryKey(),
    customer: uuid("customer_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    deliveryAddress: uuid("delivery_address_id")
      .notNull()
      .references(() => addresses.id, {
        onDelete: "set null",
      }),
    paymentStatus: enum_orders_payment_status("payment_status")
      .notNull()
      .default("unpaid"),
    paystackAccessCode: varchar("paystack_access_code"),
    snapshot: jsonb("snapshot").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("orders_customer_idx").on(columns.customer),
    index("orders_delivery_address_idx").on(columns.deliveryAddress),
    index("orders_updated_at_idx").on(columns.updatedAt),
    index("orders_created_at_idx").on(columns.createdAt),
  ]
)

export const order_statuses = pgTable(
  "order_statuses",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    order: numeric("order_id", { mode: "number" })
      .notNull()
      .references(() => orders.id, {
        onDelete: "set null",
      }),
    staff: uuid("staff_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    status: enum_order_statuses_status("status").notNull().default("pending"),
    visibleToCustomer: boolean("visible_to_customer").notNull().default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("order_statuses_order_idx").on(columns.order),
    index("order_statuses_staff_idx").on(columns.staff),
    index("order_statuses_updated_at_idx").on(columns.updatedAt),
    index("order_statuses_created_at_idx").on(columns.createdAt),
  ]
)

export const transactions = pgTable(
  "transactions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    order: numeric("order_id", { mode: "number" })
      .notNull()
      .references(() => orders.id, {
        onDelete: "set null",
      }),
    amount: numeric("amount", { mode: "number" }).notNull(),
    ref: varchar("ref").notNull(),
    provider: varchar("provider").notNull(),
    isTest: boolean("is_test").default(false),
    paidAt: timestamp("paid_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    snapshot: jsonb("snapshot").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("transactions_order_idx").on(columns.order),
    index("transactions_updated_at_idx").on(columns.updatedAt),
    index("transactions_created_at_idx").on(columns.createdAt),
  ]
)

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)]
)

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ]
)

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: uuid("users_id"),
    addressesID: uuid("addresses_id"),
    mediaID: uuid("media_id"),
    packagesID: uuid("packages_id"),
    "service-areasID": uuid("service_areas_id"),
    brandsID: uuid("brands_id"),
    categoriesID: uuid("categories_id"),
    productsID: uuid("products_id"),
    "product-variantsID": uuid("product_variants_id"),
    "stock-alertsID": uuid("stock_alerts_id"),
    wishlistsID: uuid("wishlists_id"),
    cartsID: uuid("carts_id"),
    ordersID: numeric("orders_id", { mode: "number" }),
    "order-statusesID": uuid("order_statuses_id"),
    transactionsID: uuid("transactions_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_addresses_id_idx").on(
      columns.addressesID
    ),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_packages_id_idx").on(
      columns.packagesID
    ),
    index("payload_locked_documents_rels_service_areas_id_idx").on(
      columns["service-areasID"]
    ),
    index("payload_locked_documents_rels_brands_id_idx").on(columns.brandsID),
    index("payload_locked_documents_rels_categories_id_idx").on(
      columns.categoriesID
    ),
    index("payload_locked_documents_rels_products_id_idx").on(
      columns.productsID
    ),
    index("payload_locked_documents_rels_product_variants_id_idx").on(
      columns["product-variantsID"]
    ),
    index("payload_locked_documents_rels_stock_alerts_id_idx").on(
      columns["stock-alertsID"]
    ),
    index("payload_locked_documents_rels_wishlists_id_idx").on(
      columns.wishlistsID
    ),
    index("payload_locked_documents_rels_carts_id_idx").on(columns.cartsID),
    index("payload_locked_documents_rels_orders_id_idx").on(columns.ordersID),
    index("payload_locked_documents_rels_order_statuses_id_idx").on(
      columns["order-statusesID"]
    ),
    index("payload_locked_documents_rels_transactions_id_idx").on(
      columns.transactionsID
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["addressesID"]],
      foreignColumns: [addresses.id],
      name: "payload_locked_documents_rels_addresses_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["packagesID"]],
      foreignColumns: [packages.id],
      name: "payload_locked_documents_rels_packages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["service-areasID"]],
      foreignColumns: [service_areas.id],
      name: "payload_locked_documents_rels_service_areas_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["brandsID"]],
      foreignColumns: [brands.id],
      name: "payload_locked_documents_rels_brands_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["categoriesID"]],
      foreignColumns: [categories.id],
      name: "payload_locked_documents_rels_categories_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["productsID"]],
      foreignColumns: [products.id],
      name: "payload_locked_documents_rels_products_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["product-variantsID"]],
      foreignColumns: [product_variants.id],
      name: "payload_locked_documents_rels_product_variants_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["stock-alertsID"]],
      foreignColumns: [stock_alerts.id],
      name: "payload_locked_documents_rels_stock_alerts_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["wishlistsID"]],
      foreignColumns: [wishlists.id],
      name: "payload_locked_documents_rels_wishlists_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["cartsID"]],
      foreignColumns: [carts.id],
      name: "payload_locked_documents_rels_carts_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["ordersID"]],
      foreignColumns: [orders.id],
      name: "payload_locked_documents_rels_orders_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["order-statusesID"]],
      foreignColumns: [order_statuses.id],
      name: "payload_locked_documents_rels_order_statuses_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["transactionsID"]],
      foreignColumns: [transactions.id],
      name: "payload_locked_documents_rels_transactions_fk",
    }).onDelete("cascade"),
  ]
)

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ]
)

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: uuid("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ]
)

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ]
)

export const settings = pgTable("settings", {
  id: uuid("id").defaultRandom().primaryKey(),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
})

export const settings_texts = pgTable(
  "settings_texts",
  {
    id: serial("id").primaryKey(),
    order: integer("order").notNull(),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    text: varchar("text"),
  },
  (columns) => [
    index("settings_texts_order_parent").on(columns.order, columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [settings.id],
      name: "settings_texts_parent_fk",
    }).onDelete("cascade"),
  ]
)

export const nav_items = pgTable(
  "nav_items",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
    url: varchar("url").notNull(),
  },
  (columns) => [
    index("nav_items_order_idx").on(columns._order),
    index("nav_items_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [nav.id],
      name: "nav_items_parent_id_fk",
    }).onDelete("cascade"),
  ]
)

export const nav = pgTable("nav", {
  id: uuid("id").defaultRandom().primaryKey(),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
})

export const footer_nav_links = pgTable(
  "footer_nav_links",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
    url: varchar("url").notNull(),
  },
  (columns) => [
    index("footer_nav_links_order_idx").on(columns._order),
    index("footer_nav_links_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [footer_nav.id],
      name: "footer_nav_links_parent_id_fk",
    }).onDelete("cascade"),
  ]
)

export const footer_nav = pgTable(
  "footer_nav",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
  },
  (columns) => [
    index("footer_nav_order_idx").on(columns._order),
    index("footer_nav_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [footer.id],
      name: "footer_nav_parent_id_fk",
    }).onDelete("cascade"),
  ]
)

export const footer = pgTable("footer", {
  id: uuid("id").defaultRandom().primaryKey(),
  tagline: varchar("tagline").notNull(),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
})

export const relations_users_roles = relations(users_roles, ({ one }) => ({
  parent: one(users, {
    fields: [users_roles.parent],
    references: [users.id],
    relationName: "roles",
  }),
}))
export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  })
)
export const relations_users = relations(users, ({ many }) => ({
  roles: many(users_roles, {
    relationName: "roles",
  }),
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}))
export const relations_addresses = relations(addresses, ({ one }) => ({
  user: one(users, {
    fields: [addresses.user],
    references: [users.id],
    relationName: "user",
  }),
}))
export const relations_media_texts = relations(media_texts, ({ one }) => ({
  parent: one(media, {
    fields: [media_texts.parent],
    references: [media.id],
    relationName: "_texts",
  }),
}))
export const relations_media = relations(media, ({ many }) => ({
  _texts: many(media_texts, {
    relationName: "_texts",
  }),
}))
export const relations_packages = relations(packages, () => ({}))
export const relations_service_areas_shipping_rates = relations(
  service_areas_shipping_rates,
  ({ one }) => ({
    _parentID: one(service_areas, {
      fields: [service_areas_shipping_rates._parentID],
      references: [service_areas.id],
      relationName: "shippingRates",
    }),
    package: one(packages, {
      fields: [service_areas_shipping_rates.package],
      references: [packages.id],
      relationName: "package",
    }),
  })
)
export const relations_service_areas = relations(service_areas, ({ many }) => ({
  shippingRates: many(service_areas_shipping_rates, {
    relationName: "shippingRates",
  }),
}))
export const relations_brands = relations(brands, ({ one }) => ({
  logo: one(media, {
    fields: [brands.logo],
    references: [media.id],
    relationName: "logo",
  }),
}))
export const relations_categories_type = relations(
  categories_type,
  ({ one }) => ({
    parent: one(categories, {
      fields: [categories_type.parent],
      references: [categories.id],
      relationName: "type",
    }),
  })
)
export const relations_categories = relations(categories, ({ many }) => ({
  type: many(categories_type, {
    relationName: "type",
  }),
}))
export const relations_products_rels = relations(products_rels, ({ one }) => ({
  parent: one(products, {
    fields: [products_rels.parent],
    references: [products.id],
    relationName: "_rels",
  }),
  mediaID: one(media, {
    fields: [products_rels.mediaID],
    references: [media.id],
    relationName: "media",
  }),
  categoriesID: one(categories, {
    fields: [products_rels.categoriesID],
    references: [categories.id],
    relationName: "categories",
  }),
}))
export const relations_products = relations(products, ({ one, many }) => ({
  brand: one(brands, {
    fields: [products.brand],
    references: [brands.id],
    relationName: "brand",
  }),
  _rels: many(products_rels, {
    relationName: "_rels",
  }),
}))
export const relations_product_variants_rels = relations(
  product_variants_rels,
  ({ one }) => ({
    parent: one(product_variants, {
      fields: [product_variants_rels.parent],
      references: [product_variants.id],
      relationName: "_rels",
    }),
    mediaID: one(media, {
      fields: [product_variants_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
  })
)
export const relations_product_variants = relations(
  product_variants,
  ({ one, many }) => ({
    product: one(products, {
      fields: [product_variants.product],
      references: [products.id],
      relationName: "product",
    }),
    _rels: many(product_variants_rels, {
      relationName: "_rels",
    }),
  })
)
export const relations_stock_alerts = relations(stock_alerts, ({ one }) => ({
  user: one(users, {
    fields: [stock_alerts.user],
    references: [users.id],
    relationName: "user",
  }),
  productVariant: one(product_variants, {
    fields: [stock_alerts.productVariant],
    references: [product_variants.id],
    relationName: "productVariant",
  }),
}))
export const relations_wishlists = relations(wishlists, ({ one }) => ({
  customer: one(users, {
    fields: [wishlists.customer],
    references: [users.id],
    relationName: "customer",
  }),
  productVariant: one(product_variants, {
    fields: [wishlists.productVariant],
    references: [product_variants.id],
    relationName: "productVariant",
  }),
}))
export const relations_carts_items = relations(carts_items, ({ one }) => ({
  _parentID: one(carts, {
    fields: [carts_items._parentID],
    references: [carts.id],
    relationName: "items",
  }),
  productVariant: one(product_variants, {
    fields: [carts_items.productVariant],
    references: [product_variants.id],
    relationName: "productVariant",
  }),
}))
export const relations_carts = relations(carts, ({ one, many }) => ({
  customer: one(users, {
    fields: [carts.customer],
    references: [users.id],
    relationName: "customer",
  }),
  items: many(carts_items, {
    relationName: "items",
  }),
}))
export const relations_orders_items = relations(orders_items, ({ one }) => ({
  _parentID: one(orders, {
    fields: [orders_items._parentID],
    references: [orders.id],
    relationName: "items",
  }),
  productVariant: one(product_variants, {
    fields: [orders_items.productVariant],
    references: [product_variants.id],
    relationName: "productVariant",
  }),
}))
export const relations_orders = relations(orders, ({ one, many }) => ({
  customer: one(users, {
    fields: [orders.customer],
    references: [users.id],
    relationName: "customer",
  }),
  deliveryAddress: one(addresses, {
    fields: [orders.deliveryAddress],
    references: [addresses.id],
    relationName: "deliveryAddress",
  }),
  items: many(orders_items, {
    relationName: "items",
  }),
}))
export const relations_order_statuses = relations(
  order_statuses,
  ({ one }) => ({
    order: one(orders, {
      fields: [order_statuses.order],
      references: [orders.id],
      relationName: "order",
    }),
    staff: one(users, {
      fields: [order_statuses.staff],
      references: [users.id],
      relationName: "staff",
    }),
  })
)
export const relations_transactions = relations(transactions, ({ one }) => ({
  order: one(orders, {
    fields: [transactions.order],
    references: [orders.id],
    relationName: "order",
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    addressesID: one(addresses, {
      fields: [payload_locked_documents_rels.addressesID],
      references: [addresses.id],
      relationName: "addresses",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    packagesID: one(packages, {
      fields: [payload_locked_documents_rels.packagesID],
      references: [packages.id],
      relationName: "packages",
    }),
    "service-areasID": one(service_areas, {
      fields: [payload_locked_documents_rels["service-areasID"]],
      references: [service_areas.id],
      relationName: "service-areas",
    }),
    brandsID: one(brands, {
      fields: [payload_locked_documents_rels.brandsID],
      references: [brands.id],
      relationName: "brands",
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: "categories",
    }),
    productsID: one(products, {
      fields: [payload_locked_documents_rels.productsID],
      references: [products.id],
      relationName: "products",
    }),
    "product-variantsID": one(product_variants, {
      fields: [payload_locked_documents_rels["product-variantsID"]],
      references: [product_variants.id],
      relationName: "product-variants",
    }),
    "stock-alertsID": one(stock_alerts, {
      fields: [payload_locked_documents_rels["stock-alertsID"]],
      references: [stock_alerts.id],
      relationName: "stock-alerts",
    }),
    wishlistsID: one(wishlists, {
      fields: [payload_locked_documents_rels.wishlistsID],
      references: [wishlists.id],
      relationName: "wishlists",
    }),
    cartsID: one(carts, {
      fields: [payload_locked_documents_rels.cartsID],
      references: [carts.id],
      relationName: "carts",
    }),
    ordersID: one(orders, {
      fields: [payload_locked_documents_rels.ordersID],
      references: [orders.id],
      relationName: "orders",
    }),
    "order-statusesID": one(order_statuses, {
      fields: [payload_locked_documents_rels["order-statusesID"]],
      references: [order_statuses.id],
      relationName: "order-statuses",
    }),
    transactionsID: one(transactions, {
      fields: [payload_locked_documents_rels.transactionsID],
      references: [transactions.id],
      relationName: "transactions",
    }),
  })
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  })
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  })
)
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  })
)
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({})
)
export const relations_settings_texts = relations(
  settings_texts,
  ({ one }) => ({
    parent: one(settings, {
      fields: [settings_texts.parent],
      references: [settings.id],
      relationName: "_texts",
    }),
  })
)
export const relations_settings = relations(settings, ({ many }) => ({
  _texts: many(settings_texts, {
    relationName: "_texts",
  }),
}))
export const relations_nav_items = relations(nav_items, ({ one }) => ({
  _parentID: one(nav, {
    fields: [nav_items._parentID],
    references: [nav.id],
    relationName: "items",
  }),
}))
export const relations_nav = relations(nav, ({ many }) => ({
  items: many(nav_items, {
    relationName: "items",
  }),
}))
export const relations_footer_nav_links = relations(
  footer_nav_links,
  ({ one }) => ({
    _parentID: one(footer_nav, {
      fields: [footer_nav_links._parentID],
      references: [footer_nav.id],
      relationName: "links",
    }),
  })
)
export const relations_footer_nav = relations(footer_nav, ({ one, many }) => ({
  _parentID: one(footer, {
    fields: [footer_nav._parentID],
    references: [footer.id],
    relationName: "nav",
  }),
  links: many(footer_nav_links, {
    relationName: "links",
  }),
}))
export const relations_footer = relations(footer, ({ many }) => ({
  nav: many(footer_nav, {
    relationName: "nav",
  }),
}))

type DatabaseSchema = {
  enum_users_roles: typeof enum_users_roles
  enum_users_gender: typeof enum_users_gender
  enum_addresses_title: typeof enum_addresses_title
  enum_categories_type: typeof enum_categories_type
  enum_orders_payment_status: typeof enum_orders_payment_status
  enum_order_statuses_status: typeof enum_order_statuses_status
  users_roles: typeof users_roles
  users_sessions: typeof users_sessions
  users: typeof users
  addresses: typeof addresses
  media: typeof media
  media_texts: typeof media_texts
  packages: typeof packages
  service_areas_shipping_rates: typeof service_areas_shipping_rates
  service_areas: typeof service_areas
  brands: typeof brands
  categories_type: typeof categories_type
  categories: typeof categories
  products: typeof products
  products_rels: typeof products_rels
  product_variants: typeof product_variants
  product_variants_rels: typeof product_variants_rels
  stock_alerts: typeof stock_alerts
  wishlists: typeof wishlists
  carts_items: typeof carts_items
  carts: typeof carts
  orders_items: typeof orders_items
  orders: typeof orders
  order_statuses: typeof order_statuses
  transactions: typeof transactions
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  settings: typeof settings
  settings_texts: typeof settings_texts
  nav_items: typeof nav_items
  nav: typeof nav
  footer_nav_links: typeof footer_nav_links
  footer_nav: typeof footer_nav
  footer: typeof footer
  relations_users_roles: typeof relations_users_roles
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_addresses: typeof relations_addresses
  relations_media_texts: typeof relations_media_texts
  relations_media: typeof relations_media
  relations_packages: typeof relations_packages
  relations_service_areas_shipping_rates: typeof relations_service_areas_shipping_rates
  relations_service_areas: typeof relations_service_areas
  relations_brands: typeof relations_brands
  relations_categories_type: typeof relations_categories_type
  relations_categories: typeof relations_categories
  relations_products_rels: typeof relations_products_rels
  relations_products: typeof relations_products
  relations_product_variants_rels: typeof relations_product_variants_rels
  relations_product_variants: typeof relations_product_variants
  relations_stock_alerts: typeof relations_stock_alerts
  relations_wishlists: typeof relations_wishlists
  relations_carts_items: typeof relations_carts_items
  relations_carts: typeof relations_carts
  relations_orders_items: typeof relations_orders_items
  relations_orders: typeof relations_orders
  relations_order_statuses: typeof relations_order_statuses
  relations_transactions: typeof relations_transactions
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_settings_texts: typeof relations_settings_texts
  relations_settings: typeof relations_settings
  relations_nav_items: typeof relations_nav_items
  relations_nav: typeof relations_nav
  relations_footer_nav_links: typeof relations_footer_nav_links
  relations_footer_nav: typeof relations_footer_nav
  relations_footer: typeof relations_footer
}

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
